# Generated by Django 5.2.5 on 2025-09-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
